project_id = "lvefgadeywiktazmukgk"

[functions.create-user]
enabled = true
verify_jwt = true
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-user/*.html" ]
